### ISSUE TITLE
如何集成到自己的项目里？

### ISSUE THREAD

**Issue by menghanshi** [safe-ending/BankCardScanner-master#1]
扫描银行卡功能，我集成到自己的项目中，报 java.lang.UnsatisfiedLinkError: No implementation found for int XXX.bankcard.BankCardAPI.WTInitCardKernal(java.lang.String, int) (tried Java_XXX_bankcard_BankCardAPI_WTInitCardKernal and Java_XXX_bankcard_BankCardAPI_WTInitCardKernal__Ljava_lang_String_2I，在网上查了下，好像是.so文件包名不对，看了你的项目包名，和ScanCamera扫描银行卡功能的作者的包名一样，所以问下，你在其他包名的项目中试过了这个功能么？主要是不知道在哪里修改这个错误，对jni这块儿不熟悉。。。。

**Comment by safe-ending** [comment]
你只要保证目录包一样就没问题的，保证这个包名为com.wintone..这种就行了

**Comment by menghanshi** [comment]
改自己项目的包名不现实，我最后是将整个Demo 打成aar文件，再添加依赖到自己的项目里解决的
